[package]
name = "rustbook"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
actix-files = "0.6.2"
actix-cors = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.9"
